// tslint:disable
/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, OperationOpts, RawAjaxResponse } from '../runtime';

/**
 * no description
 */
export class DefaultApi extends BaseAPI {

    /**
     * Optional extended description in CommonMark or HTML.
     * Returns a list of users.
     */
    usersGet(): Observable<Array<string>>
    usersGet(opts?: OperationOpts): Observable<RawAjaxResponse<Array<string>>>
    usersGet(opts?: OperationOpts): Observable<Array<string> | RawAjaxResponse<Array<string>>> {
        return this.request<Array<string>>({
            url: '/users',
            method: 'GET',
        }, opts?.responseOpts);
    };

}
